version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: 'mongodb://prisma:prisma@mongo'

  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo

  redis:
    image: redis
    expose:
      - 6739

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    container_name: backend
    ports:
      - 4000:4000
    links:
      - redis
      - prisma
    depends_on:
      - redis
      - prisma
    environment:
      - NODE_ENV=development
      - PORT=4000
      - REDIS_HOST=redis

volumes:
  mongo:
